import Nav from "./auth/Nav";
import "./globals.css";
import { Roboto } from "next/font/google";
import QueryWrapper from "./lib/QueryQrapper";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} mx-4 md:mx-48 xl:mx-96 bg-slate-100 `}
      >
        <QueryWrapper>
          <Nav />
          {children}
        </QueryWrapper>
      </body>
    </html>
  );
}
